### ISSUE TITLE
Incorrect comment out syntax

### ISSUE THREAD

**Issue by inutano** [manabuishii/language-cwl#10]
![image](https://user-images.githubusercontent.com/221804/41386628-5f28985a-6fbd-11e8-9484-fa19f95e1fa3.png)

In Atom, `Editor: toggle line comments` does php-style comment out. They should be lines start with `#`

**Comment by manabuishii** [comment]
language-cwl 0.10.0 is fix this issue

<img width="255" alt="screen shot 2018-07-01 at 3 18 36 am" src="https://user-images.githubusercontent.com/7508005/42128021-7c0ff21a-7cdd-11e8-9282-c5d87482b419.png">

**Comment by manabuishii** [comment]
Thanks for report !! @inutano
